### ISSUE TITLE
Any plans to allow Subscription Posts to be filtered/removed?

### ISSUE THREAD

**Issue by McBobb** [rthaut/deviantART-Filter#204] opened 2022-06-24 13:53 UTC
DeviantART, again doing what nobody actually wants, is about to take away the DEVIANT WATCH page, and replace it with the far-inferior "Deviants I Watch" Page. One of the worst parts of it that ads to subscribe to a deviant's Paywalled gallery cannot be removed from that page in any way, so it would be very desirable to be able to set those to be filtered out completely, either wholesale, or by Deviant. Is that something you might be interested in adding to DeviantART Filter?

**Comment by rthaut** [comment] 2022-06-27 02:41
Duplicate of #202

**Closed by rthaut** 2022-06-27 02:41 UTC
