### ISSUE TITLE
Please add an option to filter out all pieces with no tags (to block the super lazy who use AI)

### ISSUE THREAD

**Issue by linlinxza** [rthaut/deviantART-Filter#238] opened 2024-01-30 16:43 UTC
I'm noticing that lazy people who use AI are bypassing the filter because they are not using tags at all. But I am starting to think bots are on the site and are posting AI crap.

So, can you add an option to block all posts without any tags on them?

This AI shilling for making art is becoming very depressing.

**Comment by rthaut** [comment] 2024-02-01 04:01
Duplicate of #231

**Closed by rthaut** 2024-02-01 04:01 UTC

**Comment by linlinxza** [comment] 2024-02-01 05:44
> Duplicate of #231

So, there is no way to do this?
