### ISSUE TITLE
Adapt to Eclipse's coding

### ISSUE THREAD

**Issue by TotallyN0tASpy** [rthaut/deviantART-Filter#130] opened 2020-05-07 23:52 UTC
With the permanent switch to Eclipse coming soon, I really need my cringe filter up and running when I'm forced to use it.
I've noticed the filter doesn't work on Eclipse, so I'm making this issue to hopefully remind you that the permanent switch to Eclipse will make this extension obselete.

**Comment by rthaut** [comment] 2020-05-08 17:46
I actually just released the new version that works for Eclipse right around the time you raised this issue. :stuck_out_tongue_winking_eye:

The new version (v6.0.0) should be live at these links:
- https://chrome.google.com/webstore/detail/deviantart-filter/odlmamilbohnpnoomjclomghphbajikp
- https://addons.mozilla.org/en-US/firefox/addon/deviantart-filter/

**Comment by rthaut** [comment] 2020-05-12 17:26
Duplicate of #75

**Closed by rthaut** 2020-05-12 17:26 UTC
Labels: duplicate

**Comment by TotallyN0tASpy** [comment] 2020-05-12 20:45
What a relief, thanks for this amazing plugin. Now I can scroll through the
what's hot page and avoid all the you know what kind of posts.
